Controllers/FoursquareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cuatro.Common;
using Cuatro.Common.Endpoints;
using thunsaker.cuatro.demo.Models;

namespace thunsaker.cuatro.demo.Controllers {
    public class FoursquareController : Controller {
        //
        // GET: /Foursquare/
        public ActionResult Index() {
            return View();
        }

        //
        // GET: /Foursquare/Badges
        public ActionResult Badges() {
            if (Session["foursquare_access_token"] != null) {
                string accessToken = Session["foursquare_access_token"].ToString().Replace("\"", "");

                Users myUser = new Users(null, accessToken);
                List<UnlockedBadge> myUserBadges = myUser.GetBadges();
                if (myUserBadges != null && myUserBadges.Count > 0)
                    return View(myUserBadges);
                else
                    return View();
            }

            return RedirectToAction("LogOn", "FoursquareOauth");
        }

        //
        // GET: /Foursquare/Requests
        public ActionResult Requests() {
            if (Session["CurrentUser"] != null) {
                FoursquareUser currentUser = Session["CurrentUser"] as Cuatro.Common.FoursquareUser;
                string accessToken = currentUser.AccessToken;

                Users myUser = new Users(currentUser, accessToken);
                List<FriendRequest> myRequests = myUser.GetFriendRequests();

                if (myRequests != null && myRequests.Count > 0)
                    return View(myRequests);
                else
                    return View();
            }

            return RedirectToAction("LogOn", "FoursquareOauth");
        }

        //
        // GET: /Foursquare/Leaderboard
        public ActionResult Leaderboard() {
            if (Session["CurrentUser"] != null) {
                FoursquareUser currentUser = Session["CurrentUser"] as Cuatro.Common.FoursquareUser;
                string accessToken = currentUser.AccessToken;

                Users myUser = new Users(currentUser, accessToken);
                Cuatro.Common.Leaderboard myLeaderboard = myUser.GetLeaderboard();

                if (myLeaderboard != null && myLeaderboard.UsersList != null && myLeaderboard.UsersList.Count > 0)
                    return View(myLeaderboard);
                else
                    return View();
            }

            return RedirectToAction("LogOn", "FoursquareOauth");
        }

        //
        // GET: /Foursquare/UserSearch
        public ActionResult UserSearch() {
            return View();
        }

        //
        // POST: /Foursquare/UserSearch
        [HttpPost]
        public ActionResult UserSearchSubmit(FormCollection collection) {
            if (Session["CurrentUser"] != null) {
                FoursquareUser currentUser = Session["CurrentUser"] as Cuatro.Common.FoursquareUser;
                string accessToken = currentUser.AccessToken;

                Users myUser = new Users(currentUser, accessToken);
                UserSearchType type = UserSearchType.twitter;
                // TODO: Consider creating its own class (UserSearchResult or something) to order by relevance/etc
                List<FoursquareUser> resultList = new List<FoursquareUser>();
                switch (int.Parse(collection.GetValue("typeIndex").ToString())) {
                    case 1:
                        type = UserSearchType.phone;
                        break;
                    case 2:
                        type = UserSearchType.email;
                        break;
                    case 3:
                        type = UserSearchType.fbid;
                        break;
                    case 4:
                        type = UserSearchType.twitter;
                        break;
                }

                resultList = myUser.SearchUser(type, collection.GetValue("query").ToString());

                if (resultList != null)
                    return PartialView("SearchResults", resultList);
                else
                    return PartialView();
            }

            return RedirectToAction("LogOn", "FoursquareOauth");
        }

        //
        // GET: /Foursquare/Checkins
        public ActionResult Checkins() {
            if (Session["CurrentUser"] != null) {
                var daysRequest = Request["days"] ?? null;
                int days = 0;
                FoursquareUser currentUser = Session["CurrentUser"] as Cuatro.Common.FoursquareUser;
                string accessToken = currentUser.AccessToken;

                Users myUser = new Users(currentUser, accessToken);
                if (daysRequest != null) {
                    days = int.Parse(daysRequest);
                    if (days > 365)
                        days = 365;
                } else
                    days = 7;

                ViewBag.Days = days;
                List<Cuatro.Common.Checkin> myCheckins = new List<Checkin>();
                List<Cuatro.Common.Checkin> tempCheckins = myUser.GetCheckins(new TimeSpan(Math.Abs(days), 0, 0, 0), 0);
                int theOffset = 0;

                myCheckins.AddRange(tempCheckins);

                if (tempCheckins.Count == 20) {
                    while (tempCheckins.Count == 20) {
                        tempCheckins = myUser.GetCheckins(new TimeSpan(Math.Abs(days), 0, 0, 0), theOffset);
                        if (tempCheckins != null) {
                            myCheckins.AddRange(tempCheckins);
                            theOffset += 20;
                        } else
                            break;
                    }
                }

                if (myCheckins != null && myCheckins.Count > 0)
                    return View(myCheckins);
                else
                    return View();
            }

            return RedirectToAction("LogOn", "FoursquareOauth");
        }

        [HttpGet]
        public ActionResult VenueSearch() {
            return View();
        }

        [HttpPost]
        public ActionResult VenueSearch(FormCollection collection) {
            try {
                List<Venue> results = new List<Venue>();

                string query = collection["SearchQuery"] ?? "";
                string near = collection["Near"] ?? "";
                double mylat = 0.00f;
                double mylong = 0.00f;
                double.TryParse(collection["Latitude"], out mylat);
                double.TryParse(collection["Longitude"], out mylong);
                LocationCoords coords = new LocationCoords() {
                    Latitude = mylat,
                    Longitude = mylong
                };
                
                FoursquareUser currentUser = Session["CurrentUser"] as Cuatro.Common.FoursquareUser;
                string accessToken = currentUser.AccessToken;

                Venues myVenues = new Venues(currentUser, accessToken);
                
                if(mylat != 0.00f && mylong != 0.00f) {
                    results = myVenues.SearchVenues(query, coords, near);
                }

                return View(new VenueSearchModel() {
                    Latitude = mylat,
                    Longitude = mylong,
                    Near = near,
                    SearchQuery = query,
                    VenueResults = results
                });
            } catch (Exception ex) {
                return RedirectToAction("Error", "Home", new { error = "There was a problem. Ex: " + ex.Message });
                throw;
            }
        }
    }
}

Views/Foursquare/Badges.cshtml
@model IEnumerable<Cuatro.Common.UnlockedBadge>

@{
    Layout = "~/Views/Shared/_EndpointResult.cshtml";
    ViewBag.Title = "Unlocked Badges";
    
    int foursquareId = Session["foursquareId"] != null ? int.Parse(Session["foursquareId"].ToString()) : 0;
}

@section HeaderExtras {
    <script type="text/javascript">
        function showAllBadges() {
            $(document).ready(function () {
                $('#item_all').addClass('selected');
                $('#item_foursquare').removeClass('selected');
                $('#item_expertise').removeClass('selected');
                $('#item_partner').removeClass('selected');
                $('.badge-item').each(function () {
                    $(this).show();
                });
            });
        }

        function showFoursquareBadges() {
            $(document).ready(function () {
                $('#item_all').removeClass('selected');
                $('#item_foursquare').addClass('selected');
                $('#item_expertise').removeClass('selected');
                $('#item_partner').removeClass('selected');
                $('.badge-item').each(function () {
                    if($(this).hasClass('badge-foursquare'))
                        $(this).show();
                    else
                        $(this).hide();
                });
            });
        }

        function showExpertiseBadges() {
            $(document).ready(function () {
                $('#item_all').removeClass('selected');
                $('#item_foursquare').removeClass('selected');
                $('#item_expertise').addClass('selected');
                $('#item_partner').removeClass('selected');
                $('.badge-item').each(function () {
                    if ($(this).hasClass('badge-expertise'))
                        $(this).show();
                    else
                        $(this).hide();
                });
            });
        }

        function showPartnerBadges() {
            $(document).ready(function () {
                $('#item_all').removeClass('selected');
                $('#item_foursquare').removeClass('selected');
                $('#item_expertise').removeClass('selected');
                $('#item_partner').addClass('selected');
                $('.badge-item').each(function () {
                    if ($(this).hasClass('badge-partner'))
                        $(this).show();
                    else
                        $(this).hide();
                });
            });
        }
    </script>
}

@section EndpointOptions {
    <ul>
        <li id="item_all" class="selected">
            <a href="#" onclick="showAllBadges()">
                All
            </a>
        </li>
        <li id="item_foursquare">
            <a href="#" onclick="showFoursquareBadges()">
                Foursquare
            </a>
        </li>
        <li id="item_expertise">
            <a href="#" onclick="showExpertiseBadges()">
                Expertise
            </a>
        </li>
        <li id="item_partner">
            <a href="#" onclick="showPartnerBadges()">
                Partner
            </a>
        </li>
    </ul>
}

@section Results {
    <div class="badge-wrapper-inner">
        @foreach (var item in Model) {
            if (!item.Badge.ImageUri.Contains("default_off.png")) {
                <div class="badge-item badge-@item.Badge.Type.ToString("f")">
                    <a href="@String.Format("https://foursquare.com/user/{0}/badge/{1}", foursquareId, item.BadgeId)" target="_blank">
                        <img src="@String.Format(item.Badge.ImageUri, Cuatro.Common.BadgeImageSize.Small.ToString("d"))" 
                            alt="@item.Badge.Name" /><br />
                        <span class="badge-item-name">
                            @Html.DisplayFor(modelItem => item.Badge.Name)
                        </span>
                    </a><br />

                    @if (item.Checkin != null)
                    {
                        <span>
                            @item.Checkin.CreatedAt.ToShortDateString()
                            <br />
                            @if (item.Checkin.CheckinVenue != null)
                            {
                                <span>
                                    <a href="@String.Format("https://foursquare.com/v/{0}", item.Checkin.CheckinVenue.VenueId)">
                                        @if (item.Checkin.CheckinVenue.Name.Length > 15)
                                        {
                                            @item.Checkin.CheckinVenue.Name.Substring(0, 15)<span>...</span>
                                        }
                                        else
                                        {
                                            @item.Checkin.CheckinVenue.Name
                                        }
                                    </a>
                                </span>
                            }
                        </span>
                    }
                </div>
            }
        }
    </div>
        }

Views/Foursquare/Blah.cshtml
@model cuatro.common.Contact

@{
    ViewBag.Title = "Blah";
}

<h2>Blah</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Contact</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Twitter)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Twitter)
            @Html.ValidationMessageFor(model => model.Twitter)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Facebook)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Facebook)
            @Html.ValidationMessageFor(model => model.Facebook)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Foursquare/Checkins.cshtml
@model IEnumerable<Cuatro.Common.Checkin>

@{
    Layout = "~/Views/Shared/_EndpointResult.cshtml";
    ViewBag.Title = "Checkins";
}

@section HeaderExtras {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#timespan_list li').each(function () {
                $(this).removeClass('selected');
            });

            switch ($('#hidden_days').val()) {
                case "1":
                    $('#item_day').addClass('selected');
                    break;
                case "7":
                    $('#item_week').addClass('selected');
                    break;
                case "30":
                    $('#item_month').addClass('selected');
                    break;
                case "365":
                    $('#item_year').addClass('selected');
                    break;
            }
        });

        function toggleSelected(element) {
            $(document).ready(function () {
                $('#timespan_list li').each(function () {
                    if ($(this).attr('id') == element)
                        $(this).addClass('selected');
                    else
                        $(this).removeClass('selected');
                });
            });
        }
    </script>
}

@section EndpointOptions {
    <ul id="timespan_list">
        <li id="item_day">
            <a href="@Url.Action("Checkins", "Foursquare", new { days = 1 })" onclick="toggleSelected('item_day')">
                Day
            </a>
        </li>
        <li id="item_week">
            <a href="@Url.Action("Checkins", "Foursquare", new { days = 7 })" onclick="toggleSelected('item_week')">
                Week
            </a>
        </li>
        <li id="item_month" class="selected">
            <a href="@Url.Action("Checkins", "Foursquare", new { days = 30 })" onclick="toggleSelected('item_month')">
                Month
            </a>
        </li>
        <li id="item_year">
            <a href="@Url.Action("Checkins", "Foursquare", new { days = 365 })" onclick="toggleSelected('item_year')">
                Year
            </a>
        </li>
    </ul>
    <input type="hidden" name="hidden_days" id="hidden_days" value="@ViewBag.Days" />
}

@section Results {
    <div class="checkins-wrapper-inner">
        @foreach (var item in Model)
        {
            <div class="checkins-wrapper-item">
                @if(item.Private) {
                    <span>
                        <img src="@Url.Content("~/Img/lock_gray.png")" alt="Private" />&nbsp;
                    </span>
                }
            
                <span>
                    @item.CreatedAt.ToShortDateString() &nbsp;
                </span>

                @if(item.IsMayor) {
                    <span>
                        <img src="@Url.Content("~/Img/crown_blue.png")" alt="Is Mayor" />&nbsp;
                    </span>
                }
            
                <span>
                    <a href="@String.Format("https://foursquare.com/v/{0}", item.CheckinVenue.VenueId)">@item.CheckinVenue.Name</a>
                </span>

                <span class="checkin-icons">
                    @if (item.CheckinSource.Name != null) {
                        <span class="checkin-source">
                            Via <a href="@item.CheckinSource.SourceUri">@item.CheckinSource.Name</a>&nbsp;
                        </span>
                    }
                    
                    @if (item.Comments.Comments != null && item.Comments.Comments.Count() > 0) {
                        <span>
                            @*TODO: Switch this back to the blue icon if I ever make this a clickable link*@
                            @*@item.Comments.Comments.Count() <img src="@Url.Content("~/Img/comment_blue.png")" alt="Comments" />&nbsp; *@
                            @item.Comments.Comments.Count() <img src="@Url.Content("~/Img/comment_gray.png")" alt="Comments" />&nbsp;
                        </span>
                    } else {
                        <span>
                            0 <img src="@Url.Content("~/Img/comment_gray.png")" alt="Comments" />&nbsp;
                        </span>
                    }

                    @if (item.Photos.Photos != null && item.Photos.Photos.Count() > 0) {
                        <span>
                            @*TODO: Switch this back to the blue icon if I ever make this a clickable link*@
                            @*@item.Photos.Photos.Count() <img src="@Url.Content("~/Img/photo_blue.png")" alt="Photos" />*@
                            @item.Photos.Photos.Count() <img src="@Url.Content("~/Img/photo_gray.png")" alt="Photos" />
                        </span>
                    } else {
                        <span>
                            0 <img src="@Url.Content("~/Img/photo_gray.png")" alt="Photos" />
                        </span>
                    }
                </span>
                
                @if (item.Shout != null && item.Shout != "") {
                    <div class="checkin-shout">
                        "@item.Shout"
                    </div>
                }
            </div>
        }
    </div>
}

Views/Foursquare/Index.cshtml
@{
    ViewBag.Title = "User Endpoint";
}

<div class="endpoint-header">
    General
</div>
<div class="endpoint-section">
    <a href="@Url.Action("Requests")">Friend Requests</a><br />
    <a href="@Url.Action("Leaderboard")">Leaderboard</a>
    @*<a href="@Url.Action("Search")>Search Users</a>*@
</div>

<div class="endpoint-header">
    Aspects
</div>
<div class="endpoint-section">
    <a href="@Url.Action("Badges")">Get Unlocked Badges</a><br />
    <a href="@Url.Action("Checkins")">Get Checkins</a>
    @*<a href="@Url.Action("Friends")>Get Friends List</a>
    <a href="@Url.Action("Mayorships")>Get Mayorships</a>*@
</div>

Views/Foursquare/Leaderboard.cshtml
@model Cuatro.Common.Leaderboard

@{
    Layout = "~/Views/Shared/_EndpointResult.cshtml";
    ViewBag.Title = "Leaderboard";
}

@section Results {
    @foreach (var item in Model.UsersList)
    {
        <div class="leaderboard-wrapper-inner">
                <div class="leaderboard-rank">
                    #@item.Rank
                </div>
                @{Html.RenderPartial("UserInfo", item.User);}
                <div class="leaderboard-scores">
                    Recent: @item.Scores.ScoresRecentCount<br />
                    Max: @item.Scores.ScoresMaxCount<br />
                    Checkins: @item.Scores.ScoresCheckinsCount
                </div>
        
        </div>
    }
}

Views/Foursquare/Requests.cshtml
@model IEnumerable<Cuatro.Common.FriendRequest>

@{
    ViewBag.Title = "Requests";
}

<div class="badge-wrapper-outer">
@foreach (var item in Model) {
    <div class="requests-wrapper-inner">
        @{Html.RenderPartial("UserInfo", item.UserRequesting);}
    </div>
}
</div>

Views/Foursquare/UserSearch.cshtml
@{
    Layout = "~/Views/Shared/_EndpointResult.cshtml";
    ViewBag.Title = "Search";
}

@section Results {
    <div class="search-wrapper-inner-top">
        @using (Ajax.BeginForm("UserSearchSubmit", new AjaxOptions { UpdateTargetId = "div_search_results" })) {
            <fieldset>
                <span>Enter search query:</span>
                <input type="text" id="query" />
                <select id="typeIndex">
                    <option value="1">Phone</option>
                    <option value="2">Email</option>
                    <option value="3">Facebook Id</option>
                    <option value="4">Twitter</option>
                </select>
                <input type="submit" id="btn_userSearch" value="Search" />
            </fieldset>
        }
        </div>
        <div id="div_search_results" class="search-wrapper-inner-results">
            @{Html.RenderPartial("SearchResults");}
        </div>
    </div>
}

Views/Foursquare/VenueSearch.cshtml
@model thunsaker.cuatro.demo.Models.VenueSearchModel

@{
    ViewBag.Title = "Venue Search";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/gps.js")" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        GetLocation();
    });
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
        <div class="editor-label">
            @Html.LabelFor(model => model.SearchQuery)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SearchQuery)
            @Html.ValidationMessageFor(model => model.SearchQuery)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Near)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Near)
            @Html.ValidationMessageFor(model => model.Near)
        </div><br />
    
        <div class="editor-label">
            <a href="Javascript:GetLocation();" class="button">
            Locate Me
            </a>
        </div><br />

        <div class="editor-label">
            @Html.LabelFor(model => model.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Latitude)
            @Html.ValidationMessageFor(model => model.Latitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Longitude)
            @Html.ValidationMessageFor(model => model.Longitude)
        </div>

        <div>
            <input type="submit" value="Search" />
        </div>
}

@if(Model != null && Model.VenueResults != null) {
    Html.RenderPartial("VenueSearchResults", Model.VenueResults);
}

Views/Foursquare/VenueSearchResults.cshtml
@model IEnumerable<Cuatro.Common.Venue>

@{
if(Model != null) {
    <table border="1">
        <tr>
            <th>
                Foursquare Venue Id
            </th>
            <th>
                Name
            </th>
            <th>
                Item Id
            </th>
            <th>
                Verified
            </th>
            <th>
                Venue Uri
            </th>
            <th>
                Raw Json
            </th>
            <th>
                Date Created
            </th>
            <th>
                Active
            </th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FoursquareVenueId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Verified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VenueUri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RawJson)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
        </tr>
    }
    </table>

} else {
    <text>No Results</text>
}
}